name: Deploy Erimodo bot

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./ansible
          playbook: playbook.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: ${{ secrets.INVENTORY }}